import { getUserFromEvent, requireRole } from './_utils/auth.js';
import { supabase } from './_utils/supabase.js';
import { badRequest, created, forbidden, ok, optionsResponse, parseBody, requireFields, serverError, unauthorized } from './_utils/response.js';
function monthBounds(month){const [y,m]=month.split('-').map(Number);return{start:new Date(Date.UTC(y,m-1,1)).toISOString().slice(0,10),end:new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)};}
function calculate(emp,att,bonus,deductions){const salary=Number(emp.salary_amount||0), absent=att.filter(a=>a.status==='absent').length, present=att.filter(a=>['present','late'].includes(a.status)).length, half=att.filter(a=>a.status==='half_day').length, ot=att.reduce((s,a)=>s+Number(a.overtime_hours||0),0); let basic=salary,ded=0,rate=0; if(emp.salary_type==='monthly'){basic=salary; ded=absent*(salary/30); rate=salary/30/8;} else if(emp.salary_type==='daily'){basic=(present+half*.5)*salary; rate=salary/8;} else {basic=(present*8+half*4)*salary; rate=salary;} const otAmount=ot*rate; return{basic,absent,ot,otAmount,net:basic-ded+otAmount+Number(bonus||0)-Number(deductions||0)};}
export async function handler(event){
  if(event.httpMethod==='OPTIONS') return optionsResponse();
  try{const user=await getUserFromEvent(event); requireRole(user,['admin']);
    if(event.httpMethod==='GET'){const q=event.queryStringParameters||{}; let query=supabase.from('payroll').select('*, employees(name, department, designation)').order('payroll_month',{ascending:false}); if(q.month)query=query.eq('payroll_month',q.month); if(q.employee_id)query=query.eq('employee_id',q.employee_id); const {data,error}=await query; if(error)return badRequest(error.message); return ok({payroll:data});}
    if(event.httpMethod==='POST'){const body=parseBody(event); requireFields(body,['employee_id','payroll_month']); const {data:emp,error:ee}=await supabase.from('employees').select('*').eq('id',body.employee_id).single(); if(ee||!emp)return badRequest('Employee not found.'); const b=monthBounds(body.payroll_month); const {data:att,error:ae}=await supabase.from('attendance').select('*').eq('employee_id',body.employee_id).gte('attendance_date',b.start).lte('attendance_date',b.end); if(ae)return badRequest(ae.message); const calc=calculate(emp,att||[],body.bonus||0,body.deductions||0); const payload={employee_id:body.employee_id,payroll_month:body.payroll_month,basic_salary:calc.basic,absent_days:calc.absent,overtime_hours:calc.ot,overtime_amount:calc.otAmount,bonus:Number(body.bonus||0),deductions:Number(body.deductions||0),net_salary:calc.net,status:'unpaid',notes:body.notes||'',generated_by:user.id}; const {data,error}=await supabase.from('payroll').upsert(payload,{onConflict:'employee_id,payroll_month'}).select('*, employees(name, department, designation)').single(); if(error)return badRequest(error.message); return created({payroll:data});}
    if(event.httpMethod==='PUT'){const body=parseBody(event); requireFields(body,['id']); const payload={...body}; delete payload.id; if(payload.status==='paid')payload.paid_at=new Date().toISOString(); if(payload.status==='unpaid')payload.paid_at=null; const {data,error}=await supabase.from('payroll').update(payload).eq('id',body.id).select('*, employees(name, department, designation)').single(); if(error)return badRequest(error.message); return ok({payroll:data});}
    if(event.httpMethod==='DELETE'){const id=event.queryStringParameters?.id; if(!id)return badRequest('Missing id'); const {error}=await supabase.from('payroll').delete().eq('id',id); if(error)return badRequest(error.message); return ok({deleted:true});}
    return badRequest('Method not allowed');
  }catch(error){ if(error.statusCode===401)return unauthorized(error.message); if(error.statusCode===403)return forbidden(error.message); return serverError(error); }
}
