import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api.js';
import { downloadCSV } from '../lib/csv.js';
import { currentMonth, statusBadge, todayISO } from '../lib/utils.js';

export default function Attendance(){
  const [employees,setEmployees]=useState([]),[records,setRecords]=useState([]),[date,setDate]=useState(todayISO()),[month,setMonth]=useState(currentMonth()),[forms,setForms]=useState({}),[message,setMessage]=useState(''),[error,setError]=useState('');
  const summary=useMemo(()=>{const today=records.filter(r=>r.attendance_date===date);return{present:today.filter(r=>r.status==='present').length,absent:today.filter(r=>r.status==='absent').length,late:today.filter(r=>r.status==='late').length,leave:today.filter(r=>r.status==='leave').length};},[records,date]);
  async function load(){setError('');try{const [ed,ad]=await Promise.all([api.get('/employees'),api.get('/attendance',{month})]);setEmployees((ed.employees||[]).filter(e=>e.status==='active'));setRecords(ad.attendance||[]);}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[month]);
  function existing(id){return records.find(r=>r.employee_id===id&&r.attendance_date===date);}
  function form(id){return forms[id]||existing(id)||{status:'present',check_in_time:'09:00',check_out_time:'17:00',overtime_hours:0,notes:''};}
  function setEmpForm(id,k,v){setForms(c=>({...c,[id]:{...form(id),[k]:v}}));}
  async function mark(emp){try{await api.post('/attendance',{...form(emp.id),employee_id:emp.id,attendance_date:date});setMessage(`Attendance saved for ${emp.name}.`);load();}catch(e){setError(e.message);}}
  async function remove(r){try{await api.del('/attendance',{id:r.id});setMessage('Attendance deleted.');load();}catch(e){setError(e.message);}}
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black text-slate-900">Attendance</h1><p className="text-slate-500">Mark attendance and review monthly reports.</p></div><button className="btn-secondary" onClick={()=>downloadCSV('attendance.csv',records)}>Export CSV</button></div>{message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="grid gap-4 md:grid-cols-6"><div className="card md:col-span-2"><label className="label">Mark Date</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="card md:col-span-2"><label className="label">Report Month</label><input className="input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><div className="card"><p className="text-sm text-slate-500">Present</p><p className="text-2xl font-black">{summary.present}</p></div><div className="card"><p className="text-sm text-slate-500">Absent</p><p className="text-2xl font-black">{summary.absent}</p></div></div>
  <section className="card"><h2 className="mb-4 text-lg font-extrabold">Mark Attendance</h2><div className="space-y-3">{employees.map(emp=>{const f=form(emp.id);return <div key={emp.id} className="grid items-end gap-3 rounded-2xl border border-slate-200 p-3 md:grid-cols-7"><div className="md:col-span-2"><p className="font-bold">{emp.name}</p><p className="text-xs text-slate-500">{emp.department} | {emp.designation}</p></div><div><label className="label">Status</label><select className="input" value={f.status} onChange={e=>setEmpForm(emp.id,'status',e.target.value)}><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="half_day">Half day</option><option value="leave">Leave</option></select></div><div><label className="label">Check in</label><input className="input" type="time" value={f.check_in_time||''} onChange={e=>setEmpForm(emp.id,'check_in_time',e.target.value)}/></div><div><label className="label">Check out</label><input className="input" type="time" value={f.check_out_time||''} onChange={e=>setEmpForm(emp.id,'check_out_time',e.target.value)}/></div><div><label className="label">OT Hours</label><input className="input" type="number" step="0.25" value={f.overtime_hours||0} onChange={e=>setEmpForm(emp.id,'overtime_hours',e.target.value)}/></div><button className="btn-primary" onClick={()=>mark(emp)}>Save</button></div>})}</div></section>
  <section className="card"><h2 className="mb-4 text-lg font-extrabold">Monthly Attendance Report</h2><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Employee</th><th>Status</th><th>Check In</th><th>Check Out</th><th>Overtime</th><th>Action</th></tr></thead><tbody>{records.length===0&&<tr><td colSpan="7">No attendance found.</td></tr>}{records.map(r=><tr key={r.id}><td>{r.attendance_date}</td><td>{r.employees?.name}</td><td><span className={`badge ${statusBadge(r.status)}`}>{r.status}</span></td><td>{r.check_in_time}</td><td>{r.check_out_time}</td><td>{r.overtime_hours}</td><td><button className="btn-danger" onClick={()=>remove(r)}>Delete</button></td></tr>)}</tbody></table></div></section></div>;
}
