import { useEffect, useState } from 'react';
import ConfirmDialog from '../components/ConfirmDialog.jsx';
import Modal from '../components/Modal.jsx';
import { api } from '../lib/api.js';
import { downloadCSV } from '../lib/csv.js';
import { formatMoney, statusBadge, todayISO } from '../lib/utils.js';

const empty={name:'',phone:'',email:'',department:'',designation:'',joining_date:todayISO(),salary_type:'monthly',salary_amount:'',status:'active'};
export default function Employees(){
  const [employees,setEmployees]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[modal,setModal]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  async function load(){setError('');try{const d=await api.get('/employees');setEmployees(d.employees||[]);}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[]);
  const update=(k,v)=>setForm(c=>({...c,[k]:v}));
  function openCreate(){setEditing(null);setForm(empty);setModal(true);}
  function openEdit(e){setEditing(e);setForm({...empty,...e});setModal(true);}
  async function save(ev){ev.preventDefault();setError('');setMessage('');try{editing?await api.put('/employees',{...form,id:editing.id}):await api.post('/employees',form);setModal(false);setMessage(editing?'Employee updated.':'Employee added.');load();}catch(err){setError(err.message);}}
  async function remove(){try{await api.del('/employees',{id:deleting.id});setDeleting(null);setMessage('Employee deleted.');load();}catch(err){setError(err.message);}}
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black text-slate-900">Employees</h1><p className="text-slate-500">Manage staff, departments, roles, and salary rules.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>downloadCSV('employees.csv',employees)}>Export CSV</button><button className="btn-primary" onClick={openCreate}>Add Employee</button></div></div>
  {message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Contact</th><th>Department</th><th>Designation</th><th>Joining</th><th>Salary</th><th>Status</th><th>Actions</th></tr></thead><tbody>{employees.length===0&&<tr><td colSpan="8">No employees found.</td></tr>}{employees.map(e=><tr key={e.id}><td className="font-bold">{e.name}<br/><span className="text-xs font-normal text-slate-500">{e.email}</span></td><td>{e.phone}</td><td>{e.department}</td><td>{e.designation}</td><td>{e.joining_date}</td><td>{formatMoney(e.salary_amount)} / {e.salary_type}</td><td><span className={`badge ${statusBadge(e.status)}`}>{e.status}</span></td><td className="space-x-2"><button className="btn-secondary" onClick={()=>openEdit(e)}>Edit</button><button className="btn-danger" onClick={()=>setDeleting(e)}>Delete</button></td></tr>)}</tbody></table></div>
  <Modal open={modal} title={editing?'Edit Employee':'Add Employee'} onClose={()=>setModal(false)}><form onSubmit={save} className="grid gap-4 md:grid-cols-2"><div><label className="label">Name</label><input className="input" value={form.name} onChange={e=>update('name',e.target.value)} required/></div><div><label className="label">Phone</label><input className="input" value={form.phone||''} onChange={e=>update('phone',e.target.value)}/></div><div><label className="label">Email</label><input className="input" type="email" value={form.email||''} onChange={e=>update('email',e.target.value)}/></div><div><label className="label">Department</label><input className="input" value={form.department||''} onChange={e=>update('department',e.target.value)}/></div><div><label className="label">Designation</label><input className="input" value={form.designation||''} onChange={e=>update('designation',e.target.value)}/></div><div><label className="label">Joining Date</label><input className="input" type="date" value={form.joining_date} onChange={e=>update('joining_date',e.target.value)}/></div><div><label className="label">Salary Type</label><select className="input" value={form.salary_type} onChange={e=>update('salary_type',e.target.value)}><option value="monthly">Monthly</option><option value="daily">Daily</option><option value="hourly">Hourly</option></select></div><div><label className="label">Salary Amount</label><input className="input" type="number" step="0.01" value={form.salary_amount} onChange={e=>update('salary_amount',e.target.value)} required/></div><div><label className="label">Status</label><select className="input" value={form.status} onChange={e=>update('status',e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn-primary">Save</button></div></form></Modal>
  <ConfirmDialog open={!!deleting} message="This employee will be deleted permanently." onCancel={()=>setDeleting(null)} onConfirm={remove}/></div>;
}
