import { useEffect, useMemo, useState } from 'react';
import ConfirmDialog from '../components/ConfirmDialog.jsx';
import Modal from '../components/Modal.jsx';
import { api } from '../lib/api.js';
import { downloadCSV } from '../lib/csv.js';
import { formatMoney, statusBadge, todayISO } from '../lib/utils.js';

const empty={type:'income',category:'',amount:'',transaction_date:todayISO(),payment_method:'Cash',notes:''};

export default function IncomeExpenses(){
  const [rows,setRows]=useState([]),[filters,setFilters]=useState({type:'',category:'',startDate:'',endDate:''}),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[modal,setModal]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const totals=useMemo(()=>{const income=rows.filter(r=>r.type==='income').reduce((s,r)=>s+Number(r.amount||0),0); const expense=rows.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount||0),0); return {income,expense,profit:income-expense};},[rows]);
  async function load(){setError('');try{const d=await api.get('/transactions',filters);setRows(d.transactions||[]);}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[]);
  const update=(k,v)=>setForm(c=>({...c,[k]:v}));
  function openCreate(){setEditing(null);setForm(empty);setModal(true);}
  function openEdit(r){setEditing(r);setForm({...empty,...r});setModal(true);}
  async function save(e){e.preventDefault();setError('');setMessage('');try{editing?await api.put('/transactions',{...form,id:editing.id}):await api.post('/transactions',form);setModal(false);setMessage(editing?'Transaction updated.':'Transaction added.');load();}catch(err){setError(err.message);}}
  async function remove(){try{await api.del('/transactions',{id:deleting.id});setDeleting(null);setMessage('Transaction deleted.');load();}catch(err){setError(err.message);}}
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black text-slate-900">Income & Expenses</h1><p className="text-slate-500">Add, edit, delete, filter, and export transactions.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>downloadCSV('transactions.csv',rows)}>Export CSV</button><button className="btn-primary" onClick={openCreate}>Add Transaction</button></div></div>
  {message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-3"><div className="card"><p className="text-sm text-slate-500">Income</p><p className="text-2xl font-black">{formatMoney(totals.income)}</p></div><div className="card"><p className="text-sm text-slate-500">Expenses</p><p className="text-2xl font-black">{formatMoney(totals.expense)}</p></div><div className="card"><p className="text-sm text-slate-500">Profit</p><p className="text-2xl font-black">{formatMoney(totals.profit)}</p></div></div>
  <div className="card grid gap-3 md:grid-cols-5"><select className="input" value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">All types</option><option value="income">Income</option><option value="expense">Expense</option></select><input className="input" placeholder="Category" value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}/><input className="input" type="date" value={filters.startDate} onChange={e=>setFilters({...filters,startDate:e.target.value})}/><input className="input" type="date" value={filters.endDate} onChange={e=>setFilters({...filters,endDate:e.target.value})}/><button className="btn-primary" onClick={load}>Apply Filters</button></div>
  <div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Amount</th><th>Payment</th><th>Notes</th><th>Actions</th></tr></thead><tbody>{rows.length===0&&<tr><td colSpan="7">No transactions found.</td></tr>}{rows.map(r=><tr key={r.id}><td>{r.transaction_date}</td><td><span className={`badge ${statusBadge(r.type)}`}>{r.type}</span></td><td>{r.category}</td><td className="font-bold">{formatMoney(r.amount)}</td><td>{r.payment_method}</td><td>{r.notes}</td><td className="space-x-2"><button className="btn-secondary" onClick={()=>openEdit(r)}>Edit</button><button className="btn-danger" onClick={()=>setDeleting(r)}>Delete</button></td></tr>)}</tbody></table></div>
  <Modal open={modal} title={editing?'Edit Transaction':'Add Transaction'} onClose={()=>setModal(false)}><form onSubmit={save} className="grid gap-4 md:grid-cols-2"><div><label className="label">Type</label><select className="input" value={form.type} onChange={e=>update('type',e.target.value)}><option value="income">Income</option><option value="expense">Expense</option></select></div><div><label className="label">Category</label><input className="input" value={form.category} onChange={e=>update('category',e.target.value)} required/></div><div><label className="label">Amount</label><input className="input" type="number" step="0.01" min="0" value={form.amount} onChange={e=>update('amount',e.target.value)} required/></div><div><label className="label">Date</label><input className="input" type="date" value={form.transaction_date} onChange={e=>update('transaction_date',e.target.value)} required/></div><div><label className="label">Payment Method</label><input className="input" value={form.payment_method||''} onChange={e=>update('payment_method',e.target.value)}/></div><div className="md:col-span-2"><label className="label">Notes</label><textarea className="input" value={form.notes||''} onChange={e=>update('notes',e.target.value)}/></div><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn-primary">Save</button></div></form></Modal>
  <ConfirmDialog open={!!deleting} message="This transaction will be deleted permanently." onCancel={()=>setDeleting(null)} onConfirm={remove}/></div>;
}
