import { useEffect, useState } from 'react';
import { api } from '../lib/api.js';
import { downloadCSV } from '../lib/csv.js';
import { currentMonth, formatMoney, statusBadge } from '../lib/utils.js';

export default function Payroll(){
  const [employees,setEmployees]=useState([]),[payroll,setPayroll]=useState([]),[form,setForm]=useState({employee_id:'',payroll_month:currentMonth(),bonus:0,deductions:0}),[message,setMessage]=useState(''),[error,setError]=useState('');
  async function load(){setError('');try{const [ed,pd]=await Promise.all([api.get('/employees'),api.get('/payroll',{month:form.payroll_month})]);setEmployees((ed.employees||[]).filter(e=>e.status==='active'));setPayroll(pd.payroll||[]);}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[form.payroll_month]);
  const update=(k,v)=>setForm(c=>({...c,[k]:v}));
  async function generate(e){e.preventDefault();setError('');setMessage('');try{await api.post('/payroll',form);setMessage('Payroll generated.');load();}catch(err){setError(err.message);}}
  async function markPaid(r){try{await api.put('/payroll',{id:r.id,status:r.status==='paid'?'unpaid':'paid'});setMessage('Payroll status updated.');load();}catch(e){setError(e.message);}}
  async function remove(r){try{await api.del('/payroll',{id:r.id});setMessage('Payroll record deleted.');load();}catch(e){setError(e.message);}}
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black text-slate-900">Payroll</h1><p className="text-slate-500">Generate salary, add bonus, deduct absent days, and mark paid/unpaid.</p></div><button className="btn-secondary" onClick={()=>downloadCSV('payroll.csv',payroll)}>Export CSV</button></div>{message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
  <form onSubmit={generate} className="card grid gap-4 md:grid-cols-5"><div><label className="label">Employee</label><select className="input" value={form.employee_id} onChange={e=>update('employee_id',e.target.value)} required><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div><div><label className="label">Month</label><input className="input" type="month" value={form.payroll_month} onChange={e=>update('payroll_month',e.target.value)} required/></div><div><label className="label">Bonus</label><input className="input" type="number" step="0.01" value={form.bonus} onChange={e=>update('bonus',e.target.value)}/></div><div><label className="label">Deductions</label><input className="input" type="number" step="0.01" value={form.deductions} onChange={e=>update('deductions',e.target.value)}/></div><button className="btn-primary self-end">Generate Salary</button></form>
  <div className="table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Month</th><th>Basic</th><th>Absent</th><th>Overtime</th><th>Bonus</th><th>Deductions</th><th>Net Salary</th><th>Status</th><th>Actions</th></tr></thead><tbody>{payroll.length===0&&<tr><td colSpan="10">No payroll generated for this month.</td></tr>}{payroll.map(r=><tr key={r.id}><td className="font-bold">{r.employees?.name}</td><td>{r.payroll_month}</td><td>{formatMoney(r.basic_salary)}</td><td>{r.absent_days}</td><td>{formatMoney(r.overtime_amount)}<br/><span className="text-xs text-slate-500">{r.overtime_hours} hrs</span></td><td>{formatMoney(r.bonus)}</td><td>{formatMoney(r.deductions)}</td><td className="font-black">{formatMoney(r.net_salary)}</td><td><span className={`badge ${statusBadge(r.status)}`}>{r.status}</span></td><td className="space-x-2"><button className="btn-secondary" onClick={()=>alert(`Salary Slip\nEmployee: ${r.employees?.name}\nMonth: ${r.payroll_month}\nNet Salary: ${formatMoney(r.net_salary)}\nStatus: ${r.status}`)}>Slip</button><button className="btn-secondary" onClick={()=>markPaid(r)}>{r.status==='paid'?'Mark Unpaid':'Mark Paid'}</button><button className="btn-danger" onClick={()=>remove(r)}>Delete</button></td></tr>)}</tbody></table></div></div>;
}
