import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';

export default function Register(){
  const [form,setForm]=useState({name:'',email:'',password:'',role:'admin'}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const {register}=useAuth(); const navigate=useNavigate(); const update=(k,v)=>setForm(c=>({...c,[k]:v}));
  async function submit(e){ e.preventDefault(); setError(''); setLoading(true); try{ await register(form); navigate('/dashboard',{replace:true}); }catch(err){ setError(err.message); }finally{ setLoading(false); } }
  return <div className="flex min-h-screen items-center justify-center bg-slate-950 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl"><div className="mb-8 text-center"><div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-600 text-xl font-black text-white">IP</div><h1 className="text-2xl font-black text-slate-900">Create your account</h1><p className="mt-2 text-sm text-slate-500">First registered user automatically becomes admin.</p></div>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<form onSubmit={submit} className="space-y-4"><div><label className="label">Name</label><input className="input" value={form.name} onChange={e=>update('name',e.target.value)} required/></div><div><label className="label">Email</label><input className="input" type="email" value={form.email} onChange={e=>update('email',e.target.value)} required/></div><div><label className="label">Password</label><input className="input" minLength="6" type="password" value={form.password} onChange={e=>update('password',e.target.value)} required/></div><div><label className="label">Role</label><select className="input" value={form.role} onChange={e=>update('role',e.target.value)}><option value="admin">Admin</option><option value="manager">Manager</option><option value="employee">Employee</option></select></div><button className="btn-primary w-full" disabled={loading}>{loading?'Creating...':'Create account'}</button></form><p className="mt-6 text-center text-sm text-slate-500">Already registered? <Link className="font-bold text-brand-700" to="/login">Login</Link></p></div></div>;
}
