import { useState } from 'react';
import { api } from '../lib/api.js';
import { downloadCSV } from '../lib/csv.js';
import { formatMoney, todayISO } from '../lib/utils.js';

export default function Reports(){
  const [filters,setFilters]=useState({type:'profit',startDate:'',endDate:todayISO()}),[report,setReport]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  async function run(){setLoading(true);setError('');try{setReport(await api.get('/reports',filters));}catch(e){setError(e.message);}finally{setLoading(false);}}
  const rows=report?.rows||[];
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black text-slate-900">Reports</h1><p className="text-slate-500">Generate finance, stock, low stock, attendance, and payroll reports.</p></div><button className="btn-secondary" onClick={()=>downloadCSV(`${filters.type}-report.csv`,rows)}>Export CSV</button></div>{error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="card grid gap-4 md:grid-cols-4"><div><label className="label">Report Type</label><select className="input" value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="profit">Profit Report</option><option value="income">Income Report</option><option value="expense">Expense Report</option><option value="stock">Stock Report</option><option value="low_stock">Low Stock Report</option><option value="attendance">Attendance Report</option><option value="payroll">Payroll Report</option></select></div><div><label className="label">Start Date</label><input className="input" type="date" value={filters.startDate} onChange={e=>setFilters({...filters,startDate:e.target.value})}/></div><div><label className="label">End Date</label><input className="input" type="date" value={filters.endDate} onChange={e=>setFilters({...filters,endDate:e.target.value})}/></div><button className="btn-primary self-end" onClick={run}>{loading?'Generating...':'Generate Report'}</button></div>
  {report&&<div className="grid gap-4 md:grid-cols-3">{Object.entries(report.summary||{}).map(([k,v])=><div className="card" key={k}><p className="text-sm capitalize text-slate-500">{k.replaceAll('_',' ')}</p><p className="text-2xl font-black">{typeof v==='number' && /(amount|profit|income|expense|value|salary)/.test(k)?formatMoney(v):v}</p></div>)}</div>}
  <div className="table-wrap"><table className="table"><thead><tr>{rows[0]?Object.keys(rows[0]).map(k=><th key={k}>{k.replaceAll('_',' ')}</th>):<th>Report data</th>}</tr></thead><tbody>{!report&&<tr><td>Choose a report and click Generate Report.</td></tr>}{report&&rows.length===0&&<tr><td>No data found.</td></tr>}{rows.map((row,i)=><tr key={i}>{Object.entries(row).map(([k,v])=><td key={k}>{typeof v==='object'&&v!==null?JSON.stringify(v):String(v??'')}</td>)}</tr>)}</tbody></table></div></div>;
}
