import { useEffect, useState } from 'react';
import { api } from '../lib/api.js';

export default function Settings(){
  const [form,setForm]=useState({business_name:'',currency:'USD',business_address:'',low_stock_alert:true,admin_name:'',admin_email:''}),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{api.get('/settings').then(d=>setForm(c=>({...c,...(d.settings||{})}))).catch(e=>setError(e.message));},[]);
  const update=(k,v)=>setForm(c=>({...c,[k]:v}));
  async function save(e){e.preventDefault();setMessage('');setError('');try{const d=await api.put('/settings',form);setForm(d.settings);setMessage('Settings saved.');}catch(err){setError(err.message);}}
  return <div className="space-y-6"><div><h1 className="text-2xl font-black text-slate-900">Settings</h1><p className="text-slate-500">Update business profile, currency, address, and alerts.</p></div>{message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}<form onSubmit={save} className="card grid gap-4 md:grid-cols-2"><div><label className="label">Business Name</label><input className="input" value={form.business_name||''} onChange={e=>update('business_name',e.target.value)} required/></div><div><label className="label">Currency</label><select className="input" value={form.currency||'USD'} onChange={e=>update('currency',e.target.value)}><option value="USD">USD</option><option value="PKR">PKR</option><option value="AED">AED</option><option value="GBP">GBP</option><option value="EUR">EUR</option></select></div><div className="md:col-span-2"><label className="label">Business Address</label><textarea className="input" value={form.business_address||''} onChange={e=>update('business_address',e.target.value)}/></div><div><label className="label">Admin Name</label><input className="input" value={form.admin_name||''} onChange={e=>update('admin_name',e.target.value)}/></div><div><label className="label">Admin Email</label><input className="input" type="email" value={form.admin_email||''} onChange={e=>update('admin_email',e.target.value)}/></div><label className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" checked={!!form.low_stock_alert} onChange={e=>update('low_stock_alert',e.target.checked)}/><span className="font-semibold text-slate-700">Enable low stock alerts</span></label><div className="md:col-span-2"><button className="btn-primary">Save Settings</button></div></form></div>;
}
