import { useEffect, useMemo, useState } from 'react';
import ConfirmDialog from '../components/ConfirmDialog.jsx';
import Modal from '../components/Modal.jsx';
import { api } from '../lib/api.js';
import { downloadCSV } from '../lib/csv.js';
import { formatMoney } from '../lib/utils.js';

const emptyProduct={name:'',sku:'',category:'',unit:'pcs',purchase_price:'',selling_price:'',quantity:'',minimum_stock_level:'',supplier:''};
const emptyMovement={product_id:'',movement_type:'stock_in',quantity:'',note:''};

export default function Stock(){
  const [products,setProducts]=useState([]),[movements,setMovements]=useState([]),[form,setForm]=useState(emptyProduct),[movement,setMovement]=useState(emptyMovement),[editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[productModal,setProductModal]=useState(false),[movementModal,setMovementModal]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const lowStock=useMemo(()=>products.filter(p=>Number(p.quantity)<=Number(p.minimum_stock_level)),[products]);
  const stockValue=useMemo(()=>products.reduce((s,p)=>s+Number(p.quantity||0)*Number(p.purchase_price||0),0),[products]);
  async function load(){setError('');try{const [pd,md]=await Promise.all([api.get('/products'),api.get('/stock-movements')]);setProducts(pd.products||[]);setMovements(md.movements||[]);}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[]);
  function openCreate(){setEditing(null);setForm(emptyProduct);setProductModal(true);}
  function openEdit(p){setEditing(p);setForm({...emptyProduct,...p});setProductModal(true);}
  const update=(k,v)=>setForm(c=>({...c,[k]:v})); const updateMove=(k,v)=>setMovement(c=>({...c,[k]:v}));
  async function saveProduct(e){e.preventDefault();setError('');setMessage('');try{editing?await api.put('/products',{...form,id:editing.id}):await api.post('/products',form);setProductModal(false);setMessage(editing?'Product updated.':'Product added.');load();}catch(err){setError(err.message);}}
  async function removeProduct(){try{await api.del('/products',{id:deleting.id});setDeleting(null);setMessage('Product deleted.');load();}catch(err){setError(err.message);}}
  function openMovement(p=null,type='stock_in'){setMovement({...emptyMovement,product_id:p?.id||'',movement_type:type});setMovementModal(true);}
  async function saveMovement(e){e.preventDefault();setError('');setMessage('');try{await api.post('/stock-movements',movement);setMovementModal(false);setMessage('Stock movement saved.');load();}catch(err){setError(err.message);}}
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-black text-slate-900">Stock Management</h1><p className="text-slate-500">Products, stock-in, stock-out, adjustment, alerts, and history.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>downloadCSV('products.csv',products)}>Export CSV</button><button className="btn-secondary" onClick={()=>openMovement()}>Stock Movement</button><button className="btn-primary" onClick={openCreate}>Add Product</button></div></div>
  {message&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="grid gap-4 md:grid-cols-3"><div className="card"><p className="text-sm text-slate-500">Products</p><p className="text-2xl font-black">{products.length}</p></div><div className="card"><p className="text-sm text-slate-500">Stock Value</p><p className="text-2xl font-black">{formatMoney(stockValue)}</p></div><div className="card"><p className="text-sm text-slate-500">Low Stock Alerts</p><p className="text-2xl font-black text-amber-600">{lowStock.length}</p></div></div>
  <div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Unit</th><th>Purchase</th><th>Selling</th><th>Qty</th><th>Min</th><th>Supplier</th><th>Actions</th></tr></thead><tbody>{products.length===0&&<tr><td colSpan="10">No products found.</td></tr>}{products.map(p=><tr key={p.id} className={Number(p.quantity)<=Number(p.minimum_stock_level)?'bg-amber-50/60':''}><td className="font-bold">{p.name}</td><td>{p.sku}</td><td>{p.category}</td><td>{p.unit}</td><td>{formatMoney(p.purchase_price)}</td><td>{formatMoney(p.selling_price)}</td><td>{p.quantity}</td><td>{p.minimum_stock_level}</td><td>{p.supplier}</td><td className="space-x-2"><button className="btn-secondary" onClick={()=>openMovement(p,'stock_in')}>In</button><button className="btn-secondary" onClick={()=>openMovement(p,'stock_out')}>Out</button><button className="btn-secondary" onClick={()=>openEdit(p)}>Edit</button><button className="btn-danger" onClick={()=>setDeleting(p)}>Delete</button></td></tr>)}</tbody></table></div>
  <section className="card"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-extrabold">Stock History</h2><button className="btn-secondary" onClick={()=>downloadCSV('stock-history.csv',movements)}>Export History</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Product</th><th>Type</th><th>Qty</th><th>Before</th><th>After</th><th>Note</th></tr></thead><tbody>{movements.length===0&&<tr><td colSpan="7">No movement history.</td></tr>}{movements.map(m=><tr key={m.id}><td>{m.movement_date}</td><td>{m.products?.name}</td><td>{m.movement_type}</td><td>{m.quantity}</td><td>{m.previous_quantity}</td><td>{m.new_quantity}</td><td>{m.note}</td></tr>)}</tbody></table></div></section>
  <Modal open={productModal} title={editing?'Edit Product':'Add Product'} onClose={()=>setProductModal(false)}><form onSubmit={saveProduct} className="grid gap-4 md:grid-cols-2">{Object.entries({name:'Product Name',sku:'SKU',category:'Category',unit:'Unit',purchase_price:'Purchase Price',selling_price:'Selling Price',quantity:'Quantity',minimum_stock_level:'Minimum Stock Level',supplier:'Supplier'}).map(([k,l])=><div key={k}><label className="label">{l}</label><input className="input" type={['purchase_price','selling_price','quantity','minimum_stock_level'].includes(k)?'number':'text'} step="0.01" value={form[k]||''} onChange={e=>update(k,e.target.value)} required={k!=='supplier'}/></div>)}<div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setProductModal(false)}>Cancel</button><button className="btn-primary">Save</button></div></form></Modal>
  <Modal open={movementModal} title="Stock Movement" onClose={()=>setMovementModal(false)}><form onSubmit={saveMovement} className="grid gap-4 md:grid-cols-2"><div><label className="label">Product</label><select className="input" value={movement.product_id} onChange={e=>updateMove('product_id',e.target.value)} required><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div><label className="label">Movement Type</label><select className="input" value={movement.movement_type} onChange={e=>updateMove('movement_type',e.target.value)}><option value="stock_in">Stock In</option><option value="stock_out">Stock Out</option><option value="adjustment">Adjustment - set final quantity</option></select></div><div><label className="label">Quantity</label><input className="input" type="number" step="0.01" value={movement.quantity} onChange={e=>updateMove('quantity',e.target.value)} required/></div><div><label className="label">Note</label><input className="input" value={movement.note||''} onChange={e=>updateMove('note',e.target.value)}/></div><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setMovementModal(false)}>Cancel</button><button className="btn-primary">Save Movement</button></div></form></Modal>
  <ConfirmDialog open={!!deleting} message="This product will be deleted permanently." onCancel={()=>setDeleting(null)} onConfirm={removeProduct}/></div>;
}
